-- =====================================================================
-- SETUP LENGKAP (skema + data contoh) — OSIS SMA Negeri 3 Rembang
-- Cara pakai: Supabase Dashboard -> SQL Editor -> New query ->
-- tempel SELURUH isi file ini -> Run.
-- Aman dijalankan ulang: skema bersifat idempoten dan data contoh
-- hanya dimasukkan bila tabel masih kosong.
-- JANGAN edit file ini langsung — dibuat otomatis oleh: npm run build:sql
-- =====================================================================

-- =====================================================================
-- OSIS SMA Negeri 3 Rembang 2026/2027 — Skema database Supabase
-- Jalankan di Supabase SQL Editor atau lewat `supabase db push`.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Admin (terhubung ke Supabase Auth)
-- ---------------------------------------------------------------------
create table if not exists public.admins (
  user_id    uuid primary key references auth.users (id) on delete cascade,
  name       text not null,
  email      text,
  role       text not null default 'admin' check (role in ('admin', 'superadmin')),
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (select 1 from public.admins where user_id = auth.uid());
$$;

create or replace function public.is_superadmin()
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (select 1 from public.admins where user_id = auth.uid() and role = 'superadmin');
$$;

-- ---------------------------------------------------------------------
-- Konten
-- ---------------------------------------------------------------------
create table if not exists public.settings (
  key   text primary key check (key ~ '^[a-z_]+$'),
  value jsonb
);

create table if not exists public.divisions (
  id          bigint generated by default as identity primary key,
  name        text not null,
  short       text,
  description text,
  icon        text default 'Users',
  sort_order  int default 0
);

create table if not exists public.members (
  id          bigint generated by default as identity primary key,
  name        text not null,
  position    text not null,
  class_name  text,
  division_id bigint references public.divisions (id) on delete set null,
  is_core     boolean not null default false,
  photo       text,
  instagram   text,
  quote       text,
  sort_order  int default 0
);

create table if not exists public.programs (
  id          bigint generated by default as identity primary key,
  title       text not null,
  description text,
  division_id bigint references public.divisions (id) on delete set null,
  target      text,
  start_date  date,
  end_date    date,
  status      text not null default 'rencana' check (status in ('rencana', 'berjalan', 'selesai', 'batal')),
  progress    int not null default 0 check (progress between 0 and 100)
);

create table if not exists public.posts (
  id         bigint generated by default as identity primary key,
  title      text not null,
  slug       text unique not null,
  excerpt    text,
  content    text,
  cover      text,
  category   text not null default 'Kegiatan',
  author     text,
  published  boolean not null default true,
  views      int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id          bigint generated by default as identity primary key,
  title       text not null,
  description text,
  date        date not null,
  time        time,
  location    text,
  category    text not null default 'Umum'
);

create table if not exists public.gallery (
  id         bigint generated by default as identity primary key,
  title      text,
  image      text not null,
  album      text not null default 'Umum',
  created_at timestamptz not null default now()
);

create table if not exists public.aspirations (
  id         bigint generated by default as identity primary key,
  ticket     text unique not null,
  name       text,
  class_name text,
  category   text not null default 'Umum',
  message    text not null check (char_length(message) between 10 and 2000),
  anonymous  boolean not null default false,
  status     text not null default 'baru' check (status in ('baru', 'diproses', 'selesai', 'ditolak')),
  response   text,
  ip_hash    text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists members_division_idx on public.members (division_id);
create index if not exists programs_division_idx on public.programs (division_id);
create index if not exists posts_created_idx on public.posts (created_at desc);
create index if not exists events_date_idx on public.events (date);
create index if not exists aspirations_created_idx on public.aspirations (created_at desc);
create index if not exists aspirations_ip_idx on public.aspirations (ip_hash, created_at);

-- ---------------------------------------------------------------------
-- Trigger: slug otomatis untuk berita & updated_at aspirasi
-- ---------------------------------------------------------------------
create or replace function public.slugify(txt text)
returns text
language sql immutable
as $$
  select coalesce(nullif(left(trim(both '-' from regexp_replace(lower(coalesce(txt, '')), '[^a-z0-9]+', '-', 'g')), 80), ''), 'berita');
$$;

create or replace function public.posts_set_slug()
returns trigger
language plpgsql
as $$
declare
  base text;
  candidate text;
  n int := 2;
begin
  if new.slug is null or new.slug = '' or (tg_op = 'UPDATE' and new.slug is distinct from old.slug) then
    base := public.slugify(coalesce(nullif(new.slug, ''), new.title));
    candidate := base;
    while exists (select 1 from public.posts where slug = candidate and id is distinct from new.id) loop
      candidate := base || '-' || n;
      n := n + 1;
    end loop;
    new.slug := candidate;
  end if;
  return new;
end;
$$;

drop trigger if exists posts_slug on public.posts;
create trigger posts_slug before insert or update on public.posts
  for each row execute function public.posts_set_slug();

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists aspirations_touch on public.aspirations;
create trigger aspirations_touch before update on public.aspirations
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------
alter table public.admins      enable row level security;
alter table public.settings    enable row level security;
alter table public.divisions   enable row level security;
alter table public.members     enable row level security;
alter table public.programs    enable row level security;
alter table public.posts       enable row level security;
alter table public.events      enable row level security;
alter table public.gallery     enable row level security;
alter table public.aspirations enable row level security;

-- Konten publik: semua orang boleh membaca, hanya admin yang boleh mengubah
do $$
declare t text;
begin
  foreach t in array array['settings', 'divisions', 'members', 'programs', 'events', 'gallery'] loop
    execute format('drop policy if exists "Publik dapat membaca" on public.%I', t);
    execute format('create policy "Publik dapat membaca" on public.%I for select using (true)', t);
    execute format('drop policy if exists "Admin dapat mengelola" on public.%I', t);
    execute format('create policy "Admin dapat mengelola" on public.%I for all to authenticated using (public.is_admin()) with check (public.is_admin())', t);
  end loop;
end $$;

-- Berita: publik hanya melihat yang sudah terbit
drop policy if exists "Publik membaca berita terbit" on public.posts;
create policy "Publik membaca berita terbit" on public.posts for select using (published or public.is_admin());
drop policy if exists "Admin dapat mengelola" on public.posts;
create policy "Admin dapat mengelola" on public.posts for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Aspirasi: hanya admin yang dapat mengakses tabel secara langsung.
-- Publik mengirim & melacak lewat fungsi RPC di bawah.
drop policy if exists "Admin dapat mengelola" on public.aspirations;
create policy "Admin dapat mengelola" on public.aspirations for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Admin: sesama admin boleh melihat daftar, hanya superadmin yang boleh mengubah
drop policy if exists "Admin melihat admin" on public.admins;
create policy "Admin melihat admin" on public.admins for select to authenticated using (public.is_admin());
drop policy if exists "Superadmin mengelola admin" on public.admins;
create policy "Superadmin mengelola admin" on public.admins for all to authenticated
  using (public.is_superadmin() and user_id <> auth.uid())
  with check (public.is_superadmin());

-- Hak akses dasar (RLS tetap berlaku)
grant usage on schema public to anon, authenticated;
grant select on public.settings, public.divisions, public.members, public.programs, public.posts, public.events, public.gallery to anon, authenticated;
grant insert, update, delete on public.settings, public.divisions, public.members, public.programs, public.posts, public.events, public.gallery to authenticated;
grant select, insert, update, delete on public.aspirations, public.admins to authenticated;
revoke all on public.aspirations, public.admins from anon;
grant usage, select on all sequences in schema public to authenticated;

-- ---------------------------------------------------------------------
-- Fungsi RPC publik
-- ---------------------------------------------------------------------

-- Kirim aspirasi. Mengembalikan kode tiket. Dibatasi 5 kiriman / 10 menit / IP.
create or replace function public.submit_aspiration(
  p_message   text,
  p_category  text default 'Umum',
  p_name      text default null,
  p_class     text default null,
  p_anonymous boolean default false
)
returns text
language plpgsql volatile security definer
set search_path = public
as $$
declare
  v_ticket text;
  v_ip     text;
  v_hash   text;
  v_msg    text := trim(coalesce(p_message, ''));
begin
  if char_length(v_msg) < 10 then
    raise exception 'Pesan aspirasi minimal 10 karakter' using errcode = '22023';
  end if;
  if char_length(v_msg) > 2000 then
    raise exception 'Pesan maksimal 2000 karakter' using errcode = '22023';
  end if;

  begin
    v_ip := split_part(coalesce(current_setting('request.headers', true)::json ->> 'x-forwarded-for', ''), ',', 1);
  exception when others then
    v_ip := '';
  end;
  v_hash := md5('osis-smaga:' || coalesce(nullif(trim(v_ip), ''), 'unknown'));

  if (select count(*) from public.aspirations
      where ip_hash = v_hash and created_at > now() - interval '10 minutes') >= 5 then
    raise exception 'Terlalu banyak kiriman. Coba lagi beberapa menit lagi.' using errcode = 'P0001';
  end if;

  loop
    v_ticket := 'ASP-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6));
    exit when not exists (select 1 from public.aspirations where ticket = v_ticket);
  end loop;

  insert into public.aspirations (ticket, name, class_name, category, message, anonymous, ip_hash)
  values (
    v_ticket,
    case when p_anonymous then null else nullif(left(trim(coalesce(p_name, '')), 100), '') end,
    case when p_anonymous then null else nullif(left(trim(coalesce(p_class, '')), 20), '') end,
    coalesce(nullif(left(trim(coalesce(p_category, '')), 50), ''), 'Umum'),
    v_msg,
    coalesce(p_anonymous, false),
    v_hash
  );
  return v_ticket;
end;
$$;

-- Lacak aspirasi berdasarkan kode tiket (tanpa identitas pengirim)
create or replace function public.track_aspiration(p_ticket text)
returns table (ticket text, category text, message text, status text, response text, created_at timestamptz, updated_at timestamptz)
language sql stable security definer
set search_path = public
as $$
  select a.ticket, a.category, a.message, a.status, a.response, a.created_at, a.updated_at
  from public.aspirations a
  where a.ticket = upper(trim(p_ticket));
$$;

-- Aspirasi yang sudah selesai ditindaklanjuti (ditampilkan di halaman publik)
create or replace function public.public_aspirations(p_limit int default 6)
returns table (ticket text, category text, message text, status text, response text, updated_at timestamptz)
language sql stable security definer
set search_path = public
as $$
  select a.ticket, a.category, a.message, a.status, a.response, a.updated_at
  from public.aspirations a
  where a.status = 'selesai' and coalesce(a.response, '') <> ''
  order by a.updated_at desc
  limit least(greatest(p_limit, 1), 20);
$$;

-- Statistik untuk beranda
create or replace function public.public_stats()
returns json
language sql stable security definer
set search_path = public
as $$
  select json_build_object(
    'members',          (select count(*) from public.members),
    'divisions',        (select count(*) from public.divisions),
    'programs',         (select count(*) from public.programs),
    'aspirations_done', (select count(*) from public.aspirations where status = 'selesai')
  );
$$;

-- Tambah jumlah baca berita
create or replace function public.increment_post_views(p_slug text)
returns void
language sql volatile security definer
set search_path = public
as $$
  update public.posts set views = views + 1 where slug = p_slug and published;
$$;

grant execute on function public.submit_aspiration(text, text, text, text, boolean) to anon, authenticated;
grant execute on function public.track_aspiration(text) to anon, authenticated;
grant execute on function public.public_aspirations(int) to anon, authenticated;
grant execute on function public.public_stats() to anon, authenticated;
grant execute on function public.increment_post_views(text) to anon, authenticated;
grant execute on function public.is_admin() to anon, authenticated;
grant execute on function public.is_superadmin() to anon, authenticated;

-- ---------------------------------------------------------------------
-- Storage: bucket publik "media" untuk foto & gambar
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do nothing;

drop policy if exists "Media dapat dibaca publik" on storage.objects;
create policy "Media dapat dibaca publik" on storage.objects
  for select using (bucket_id = 'media');

drop policy if exists "Admin dapat mengunggah media" on storage.objects;
create policy "Admin dapat mengunggah media" on storage.objects
  for insert to authenticated with check (bucket_id = 'media' and public.is_admin());

drop policy if exists "Admin dapat mengubah media" on storage.objects;
create policy "Admin dapat mengubah media" on storage.objects
  for update to authenticated using (bucket_id = 'media' and public.is_admin());

drop policy if exists "Admin dapat menghapus media" on storage.objects;
create policy "Admin dapat menghapus media" on storage.objects
  for delete to authenticated using (bucket_id = 'media' and public.is_admin());


-- ============================ DATA CONTOH ============================
do $seed$
begin
  if exists (select 1 from public.divisions) then
    raise notice 'Data contoh dilewati: tabel sudah berisi data';
    return;
  end if;
  -- =====================================================================
  -- Data contoh awal OSIS SMA Negeri 3 Rembang 2026/2027
  -- Semua nama pengurus adalah CONTOH — ubah melalui panel admin.
  -- Aman dijalankan sekali setelah migrasi. Jangan dijalankan ulang di
  -- database yang sudah berisi data asli.
  -- =====================================================================

  insert into public.settings (key, value) values
    ('org_name',         to_jsonb('OSIS SMA Negeri 3 Rembang'::text)),
    ('school_name',      to_jsonb('SMA Negeri 3 Rembang'::text)),
    ('period',           to_jsonb('2026/2027'::text)),
    ('cabinet_name',     to_jsonb('Kabinet Cakrawala Aksara'::text)),
    ('tagline',          to_jsonb('Bergerak Bersama, Berkarya untuk Smaga'::text)),
    ('about',            to_jsonb('Organisasi Siswa Intra Sekolah (OSIS) SMA Negeri 3 Rembang adalah wadah resmi bagi seluruh siswa untuk mengembangkan potensi, menyalurkan aspirasi, dan berperan aktif dalam membangun lingkungan sekolah yang religius, berprestasi, dan berkarakter.'::text)),
    ('vision',           to_jsonb('Mewujudkan OSIS SMA Negeri 3 Rembang sebagai organisasi yang religius, inovatif, kolaboratif, dan menjadi teladan dalam membangun budaya sekolah yang berprestasi dan berkarakter Pancasila.'::text)),
    ('missions',         '[
        "Meningkatkan keimanan dan ketakwaan warga sekolah melalui kegiatan keagamaan yang rutin dan bermakna.",
        "Menjadi jembatan aspirasi yang transparan antara siswa, guru, dan pihak sekolah.",
        "Mengembangkan minat, bakat, dan prestasi siswa di bidang akademik maupun non-akademik.",
        "Membangun budaya literasi, kreativitas, dan pemanfaatan teknologi secara positif.",
        "Menumbuhkan kepedulian sosial dan cinta lingkungan di lingkungan sekolah dan masyarakat."
      ]'::jsonb),
    ('chairman_message', to_jsonb('Assalamu’alaikum warahmatullahi wabarakatuh. Terima kasih atas kepercayaan seluruh warga SMA Negeri 3 Rembang. Bersama Kabinet Cakrawala Aksara, kami berkomitmen menghadirkan OSIS yang terbuka, mendengar, dan bergerak nyata. Mari kita wujudkan Smaga yang lebih hebat, bersama!'::text)),
    ('address',          to_jsonb('Jl. Gajah Mada No. 8, Pantiharjo, Kec. Kaliori, Kab. Rembang, Jawa Tengah'::text)),
    ('email',            to_jsonb('osis@sma3rembang.sch.id'::text)),
    ('phone',            to_jsonb('(0295) 691280'::text)),
    ('instagram',        to_jsonb('osis.smagarembang'::text)),
    ('youtube',          to_jsonb(''::text)),
    ('maps_embed',       to_jsonb('https://www.google.com/maps?q=SMA+Negeri+3+Rembang&output=embed'::text))
  on conflict (key) do nothing;

  insert into public.divisions (name, short, description, icon, sort_order) values
    ('Keimanan dan Ketakwaan terhadap Tuhan YME', 'Sekbid 1', 'Menyelenggarakan kegiatan keagamaan dan peringatan hari besar keagamaan.', 'Moon', 1),
    ('Budi Pekerti Luhur dan Akhlak Mulia', 'Sekbid 2', 'Menanamkan nilai sopan santun, disiplin, dan etika di lingkungan sekolah.', 'Heart', 2),
    ('Kepribadian Unggul, Wawasan Kebangsaan & Bela Negara', 'Sekbid 3', 'Upacara, LDKS, dan kegiatan cinta tanah air.', 'Flag', 3),
    ('Prestasi Akademik, Seni, dan Olahraga', 'Sekbid 4', 'Mengembangkan dan mewadahi prestasi siswa di berbagai bidang.', 'Trophy', 4),
    ('Demokrasi, HAM, Politik, Lingkungan Hidup & Toleransi Sosial', 'Sekbid 5', 'Pemilos, bakti sosial, dan gerakan peduli lingkungan.', 'Vote', 5),
    ('Kreativitas, Keterampilan, dan Kewirausahaan', 'Sekbid 6', 'Market day, bazar, dan pelatihan kewirausahaan siswa.', 'Lightbulb', 6),
    ('Kualitas Jasmani, Kesehatan, dan Gizi', 'Sekbid 7', 'Senam bersama, classmeeting olahraga, dan kampanye hidup sehat.', 'Activity', 7),
    ('Sastra dan Budaya', 'Sekbid 8', 'Pentas seni, bulan bahasa, dan pelestarian budaya lokal Rembang.', 'Palette', 8),
    ('Teknologi Informasi dan Komunikasi', 'Sekbid 9', 'Pengelolaan media sosial, website, dan dokumentasi OSIS.', 'Monitor', 9),
    ('Komunikasi dalam Bahasa Inggris', 'Sekbid 10', 'English day, debate club, dan lomba berbahasa Inggris.', 'Languages', 10);

  -- Pengurus inti
  insert into public.members (name, position, class_name, is_core, quote, sort_order) values
    ('Nama Ketua OSIS', 'Ketua OSIS', 'XI-1', true, 'Pemimpin yang baik adalah pendengar yang baik.', 1),
    ('Nama Wakil Ketua I', 'Wakil Ketua I', 'XI-2', true, 'Kolaborasi adalah kunci.', 2),
    ('Nama Wakil Ketua II', 'Wakil Ketua II', 'X-3', true, 'Kecil langkahnya, besar dampaknya.', 3),
    ('Nama Sekretaris I', 'Sekretaris I', 'XI-3', true, 'Rapi administrasi, lancar organisasi.', 4),
    ('Nama Sekretaris II', 'Sekretaris II', 'X-1', true, null, 5),
    ('Nama Bendahara I', 'Bendahara I', 'XI-4', true, 'Transparan dan amanah.', 6),
    ('Nama Bendahara II', 'Bendahara II', 'X-2', true, null, 7);

  -- Anggota tiap sekbid (1 koordinator + 2 anggota)
  insert into public.members (name, position, class_name, division_id, is_core, sort_order)
  select format(v.label, d.sort_order), v.position, v.class_name, d.id, false, v.ord
  from public.divisions d
  cross join (values
    ('Koordinator Sekbid %s', 'Koordinator', 'XI', 1),
    ('Anggota Sekbid %s A', 'Anggota', 'X', 2),
    ('Anggota Sekbid %s B', 'Anggota', 'X', 3)
  ) as v(label, position, class_name, ord)
  order by d.sort_order, v.ord;

  insert into public.programs (title, description, division_id, target, start_date, end_date, status, progress)
  select p.title, p.description, (select id from public.divisions where short = p.sekbid), p.target, p.start_date::date, p.end_date::date, p.status, p.progress
  from (values
    ('Jumat Berkah & Kajian Rutin', 'Kajian keagamaan dan berbagi takjil/sarapan setiap hari Jumat.', 'Sekbid 1', 'Seluruh siswa', '2026-08-01', '2027-06-30', 'berjalan', 35),
    ('Peringatan Maulid Nabi Muhammad SAW', 'Pengajian dan lomba islami dalam rangka Maulid Nabi.', 'Sekbid 1', 'Seluruh warga sekolah', '2026-08-25', '2026-08-25', 'selesai', 100),
    ('Gerakan 5S (Senyum, Sapa, Salam, Sopan, Santun)', 'Piket penyambutan siswa di gerbang sekolah setiap pagi.', 'Sekbid 2', 'Seluruh siswa', '2026-07-20', '2027-06-30', 'berjalan', 40),
    ('LDKS Pengurus OSIS & MPK', 'Latihan Dasar Kepemimpinan Siswa untuk pengurus baru.', 'Sekbid 3', 'Pengurus OSIS & MPK', '2026-10-17', '2026-10-18', 'rencana', 20),
    ('Upacara Hari Sumpah Pemuda', 'Upacara dan lomba bertema kepemudaan.', 'Sekbid 3', 'Seluruh siswa', '2026-10-28', '2026-10-28', 'rencana', 10),
    ('Smaga Cup 2026', 'Turnamen olahraga antar-kelas dan antar-SMP se-Kabupaten Rembang.', 'Sekbid 4', 'Siswa & SMP se-Rembang', '2026-11-09', '2026-11-14', 'rencana', 15),
    ('Pemilihan Ketua OSIS (Pemilos) Digital', 'Pemilihan ketua OSIS periode berikutnya secara digital dan jujur.', 'Sekbid 5', 'Seluruh siswa', '2027-08-01', '2027-08-15', 'rencana', 0),
    ('Smaga Go Green', 'Penanaman pohon, bank sampah, dan lomba kebersihan kelas.', 'Sekbid 5', 'Seluruh kelas', '2026-09-01', '2027-05-31', 'berjalan', 25),
    ('Market Day Smaga', 'Bazar kewirausahaan siswa per kelas.', 'Sekbid 6', 'Seluruh kelas', '2027-02-20', '2027-02-20', 'rencana', 0),
    ('Senam Sehat Jumat', 'Senam bersama seluruh warga sekolah.', 'Sekbid 7', 'Seluruh warga sekolah', '2026-08-01', '2027-06-30', 'berjalan', 35),
    ('Pensi & Bulan Bahasa', 'Pentas seni, musikalisasi puisi, dan lomba bahasa.', 'Sekbid 8', 'Seluruh siswa', '2026-10-01', '2026-10-31', 'rencana', 30),
    ('Smaga Media Center', 'Pengelolaan konten Instagram, TikTok, dan website OSIS.', 'Sekbid 9', 'Publik', '2026-07-15', '2027-06-30', 'berjalan', 45),
    ('English Day Every Wednesday', 'Pembiasaan berbahasa Inggris setiap hari Rabu.', 'Sekbid 10', 'Seluruh siswa', '2026-09-02', '2027-06-30', 'berjalan', 20)
  ) as p(title, description, sekbid, target, start_date, end_date, status, progress);

  insert into public.posts (title, slug, excerpt, content, category, author, created_at) values
    ('Pelantikan Pengurus OSIS Periode 2026/2027', 'pelantikan-pengurus-osis-2026-2027',
     'Pengurus OSIS SMA Negeri 3 Rembang Kabinet Cakrawala Aksara resmi dilantik oleh Kepala Sekolah.',
     E'Pengurus OSIS SMA Negeri 3 Rembang periode 2026/2027 resmi dilantik dalam upacara bendera yang diikuti seluruh warga sekolah.\n\nDalam sambutannya, Kepala Sekolah berpesan agar pengurus baru menjadi teladan, amanah, dan mampu menjadi jembatan aspirasi siswa.\n\nKetua OSIS terpilih menyampaikan komitmen untuk menjalankan program kerja yang inovatif serta membuka kanal aspirasi digital yang dapat diakses seluruh siswa melalui website ini.',
     'Organisasi', 'Sekbid 9 - TIK', '2026-08-03 08:00:00+07'),
    ('Semarak Peringatan Maulid Nabi di Smaga', 'semarak-maulid-nabi-smaga',
     'Rangkaian lomba islami dan pengajian meriahkan peringatan Maulid Nabi Muhammad SAW.',
     E'OSIS melalui Sekbid 1 menyelenggarakan peringatan Maulid Nabi Muhammad SAW dengan rangkaian lomba adzan, tartil Al-Qur’an, dan kaligrafi.\n\nAcara ditutup dengan pengajian bersama dan doa untuk kemajuan sekolah.',
     'Kegiatan', 'Sekbid 1', '2026-08-26 10:00:00+07'),
    ('Kanal Aspirasi Digital Resmi Dibuka', 'kanal-aspirasi-digital-dibuka',
     'Kini siswa dapat menyampaikan aspirasi, kritik, dan saran secara online dan dapat dilacak statusnya.',
     E'OSIS SMA Negeri 3 Rembang meluncurkan Kanal Aspirasi Digital. Siswa dapat mengirim aspirasi (boleh anonim) melalui menu Aspirasi, lalu mendapatkan kode tiket untuk memantau tindak lanjutnya.\n\nSetiap aspirasi akan dibahas dalam rapat pengurus dan ditanggapi secara terbuka.',
     'Pengumuman', 'Sekbid 9 - TIK', '2026-09-10 07:30:00+07');

  insert into public.events (title, description, date, time, location, category) values
    ('Rapat Pleno Pengurus OSIS', 'Evaluasi bulanan program kerja.', '2026-10-03', '13:30', 'Ruang OSIS', 'Rapat'),
    ('LDKS OSIS & MPK', 'Latihan Dasar Kepemimpinan Siswa.', '2026-10-17', '07:00', 'Lapangan & Aula', 'Pelatihan'),
    ('Upacara Hari Sumpah Pemuda', 'Upacara bendera memperingati Sumpah Pemuda.', '2026-10-28', '07:00', 'Lapangan Utama', 'Upacara'),
    ('Pensi Bulan Bahasa', 'Puncak acara bulan bahasa.', '2026-10-31', '08:00', 'Aula Sekolah', 'Seni'),
    ('Smaga Cup 2026', 'Turnamen futsal, voli, dan basket.', '2026-11-09', '07:30', 'GOR & Lapangan', 'Olahraga'),
    ('Peringatan Hari Guru Nasional', 'Apresiasi untuk bapak/ibu guru.', '2026-11-25', '07:00', 'Lapangan Utama', 'Upacara'),
    ('Classmeeting Semester Gasal', 'Lomba antar-kelas setelah PAS.', '2026-12-14', '07:30', 'Lingkungan Sekolah', 'Olahraga');

  insert into public.aspirations (ticket, name, class_name, category, message, anonymous, status, response) values
    ('ASP-DEMO01', null, null, 'Fasilitas', 'Mohon kran air di dekat musala diperbaiki karena sering bocor.', true, 'selesai', 'Terima kasih! Sudah diteruskan ke Waka Sarpras dan kran telah diperbaiki.'),
    ('ASP-DEMO02', 'Siswa Contoh', 'X-4', 'Kegiatan', 'Usul diadakan lomba e-sport saat classmeeting.', false, 'diproses', 'Usulan sedang dibahas bersama Sekbid 4 dan pembina.')
  on conflict (ticket) do nothing;

end
$seed$;

-- Muat ulang cache skema API agar tabel baru langsung terbaca
notify pgrst, 'reload schema';
