-- ============================================================================
-- PEMILU OSIS - SMA NEGERI 3 REMBANG
-- SUPABASE DATABASE SETUP (Jalankan di Supabase Dashboard -> SQL Editor)
-- ============================================================================

-- 1. Enable extension pgcrypto
create extension if not exists pgcrypto;

-- 2. Tabel Settings
create table if not exists public.settings (
  id int primary key default 1 check (id = 1),
  school_name text not null default 'SMA Negeri 3 Rembang',
  election_name text not null default 'Pemilihan Ketua & Wakil OSIS',
  academic_year text not null default '2025/2026',
  is_open boolean not null default true,
  show_results boolean not null default true,
  admin_password text not null default 'admin123',
  updated_at timestamptz not null default now()
);

insert into public.settings (id, school_name, election_name, academic_year, is_open, show_results, admin_password)
values (1, 'SMA Negeri 3 Rembang', 'Pemilihan Ketua & Wakil OSIS', '2025/2026', true, true, 'admin123')
on conflict (id) do nothing;

-- 3. Tabel Candidates (Pasangan Calon)
create table if not exists public.candidates (
  id bigint generated by default as identity primary key,
  num int not null unique,
  name text not null,
  class_name text not null default '',
  slogan text default '',
  visi text not null default '',
  misi jsonb not null default '[]'::jsonb,
  caption text default '',
  votes int not null default 0,
  created_at timestamptz not null default now()
);

-- 4. Tabel Voters (DPT Pemilih)
create table if not exists public.voters (
  id bigint generated by default as identity primary key,
  nis text not null unique,
  name text not null,
  class_name text not null default '',
  password text not null default 'siswa123',
  voted boolean not null default false,
  voted_at timestamptz,
  created_at timestamptz not null default now()
);

-- 5. Tabel Votes (Rekapitulasi Suara Anonim & Aman)
create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  candidate_num int not null references public.candidates(num) on delete cascade,
  created_at timestamptz not null default now()
);

-- 6. Insert Data Awal Paslon
insert into public.candidates (num, name, class_name, slogan, visi, misi, caption, votes)
values
(
  1,
  'Andi Pratama',
  'XII IPA 1',
  'Bersama Wujudkan OSIS yang Lebih Baik',
  'Terwujudnya OSIS yang inovatif dan inklusif sebagai wadah aktualisasi diri seluruh siswa SMA Negeri 3 Rembang.',
  '["Membuka ruang kreativitas melalui festival seni, budaya, dan teknologi.", "Digitalisasi pengumuman dan administrasi pengurus OSIS.", "Menampung aspirasi siswa melalui kotak saran digital terbuka."]'::jsonb,
  'ORASI SINGKAT: VISI DIGITALISASI OSIS',
  372
),
(
  2,
  'Siti Rahmawati',
  'XII IPA 2',
  'Kreatif, Kolaboratif, Berkarakter',
  'OSIS menjadi rumah kedua yang membina karakter, mengasah potensi, dan mempererat kebersamaan seluruh warga sekolah.',
  '["Program mentoring antarangkatan dan penguatan buddy system siswa baru.", "Penguatan kegiatan keagamaan dan pembiasaan akhlak terpuji.", "Lomba intra-kelas berkala untuk menjaga kekompakan angkatan."]'::jsonb,
  'ORASI SINGKAT: BUDDY SYSTEM & KEHARMONISAN SISWA',
  296
),
(
  3,
  'Budi Santoso',
  'XII IPS 1',
  'Suaramu, Wujudkan!',
  'Setiap aspirasi siswa menjadi nyata melalui program kerja OSIS yang transparan dan berbasis kebutuhan siswa.',
  '["Survei kebutuhan siswa awal semester sebagai dasar program kerja.", "Transparansi anggaran kas dan publikasi laporan kegiatan berkala.", "Revitalisasi fasilitas santai, taman baca, dan perlengkapan olahraga."]'::jsonb,
  'ORASI SINGKAT: TRANSPARANSI & FASILITAS SISWA',
  156
)
on conflict (num) do nothing;

-- 7. Insert Sampel Pemilih Awal (DPT)
insert into public.voters (nis, name, class_name, password, voted)
values
('2025001', 'Ahmad Fauzi', 'XII IPA 1', 'siswa123', true),
('2025002', 'Dewi Lestari', 'XII IPA 1', 'siswa123', true),
('2025003', 'Rizky Hidayat', 'XII IPA 2', 'siswa123', true),
('2025004', 'Nur Aini', 'XII IPA 2', 'siswa123', true),
('2025005', 'Fajar Ramadhan', 'XII IPA 2', 'siswa123', true),
('2025006', 'Putri Ayu Lestari', 'XII IPA 3', 'siswa123', true),
('2025007', 'Dimas Anggara', 'XII IPA 3', 'siswa123', true),
('2025008', 'Rina Melati', 'XII IPA 3', 'siswa123', true),
('2025009', 'Hendra Wijaya', 'XII IPS 1', 'siswa123', true),
('2025010', 'Salsabila Zahra', 'XII IPS 1', 'siswa123', false),
('2025011', 'Ikbal Firmansyah', 'XII IPS 1', 'siswa123', false),
('2025012', 'Laila Mardhiah', 'XII IPS 2', 'siswa123', false)
on conflict (nis) do nothing;

-- 8. Aturan Akses (Row Level Security & Public Access)
alter table public.settings enable row level security;
alter table public.candidates enable row level security;
alter table public.voters enable row level security;
alter table public.votes enable row level security;

-- Policy untuk read/write anon client
create policy "Allow all read settings" on public.settings for select using (true);
create policy "Allow update settings" on public.settings for update using (true);

create policy "Allow all read candidates" on public.candidates for select using (true);
create policy "Allow insert candidates" on public.candidates for insert with check (true);
create policy "Allow update candidates" on public.candidates for update using (true);
create policy "Allow delete candidates" on public.candidates for delete using (true);

create policy "Allow all read voters" on public.voters for select using (true);
create policy "Allow insert voters" on public.voters for insert with check (true);
create policy "Allow update voters" on public.voters for update using (true);
create policy "Allow delete voters" on public.voters for delete using (true);

create policy "Allow all read votes" on public.votes for select using (true);
create policy "Allow insert votes" on public.votes for insert with check (true);
