-- =====================================================================
-- OSIS SMA Negeri 3 Rembang 2026/2027 — Skema database Supabase
-- Jalankan di Supabase SQL Editor atau lewat `supabase db push`.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Admin (terhubung ke Supabase Auth)
-- ---------------------------------------------------------------------
create table if not exists public.admins (
  user_id    uuid primary key references auth.users (id) on delete cascade,
  name       text not null,
  email      text,
  role       text not null default 'admin' check (role in ('admin', 'superadmin')),
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (select 1 from public.admins where user_id = auth.uid());
$$;

create or replace function public.is_superadmin()
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (select 1 from public.admins where user_id = auth.uid() and role = 'superadmin');
$$;

-- ---------------------------------------------------------------------
-- Konten
-- ---------------------------------------------------------------------
create table if not exists public.settings (
  key   text primary key check (key ~ '^[a-z_]+$'),
  value jsonb
);

create table if not exists public.divisions (
  id          bigint generated by default as identity primary key,
  name        text not null,
  short       text,
  description text,
  icon        text default 'Users',
  sort_order  int default 0
);

create table if not exists public.members (
  id          bigint generated by default as identity primary key,
  name        text not null,
  position    text not null,
  class_name  text,
  division_id bigint references public.divisions (id) on delete set null,
  is_core     boolean not null default false,
  photo       text,
  instagram   text,
  quote       text,
  sort_order  int default 0
);

create table if not exists public.programs (
  id          bigint generated by default as identity primary key,
  title       text not null,
  description text,
  division_id bigint references public.divisions (id) on delete set null,
  target      text,
  start_date  date,
  end_date    date,
  status      text not null default 'rencana' check (status in ('rencana', 'berjalan', 'selesai', 'batal')),
  progress    int not null default 0 check (progress between 0 and 100)
);

create table if not exists public.posts (
  id         bigint generated by default as identity primary key,
  title      text not null,
  slug       text unique not null,
  excerpt    text,
  content    text,
  cover      text,
  category   text not null default 'Kegiatan',
  author     text,
  published  boolean not null default true,
  views      int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id          bigint generated by default as identity primary key,
  title       text not null,
  description text,
  date        date not null,
  time        time,
  location    text,
  category    text not null default 'Umum'
);

create table if not exists public.gallery (
  id         bigint generated by default as identity primary key,
  title      text,
  image      text not null,
  album      text not null default 'Umum',
  created_at timestamptz not null default now()
);

create table if not exists public.aspirations (
  id         bigint generated by default as identity primary key,
  ticket     text unique not null,
  name       text,
  class_name text,
  category   text not null default 'Umum',
  message    text not null check (char_length(message) between 10 and 2000),
  anonymous  boolean not null default false,
  status     text not null default 'baru' check (status in ('baru', 'diproses', 'selesai', 'ditolak')),
  response   text,
  ip_hash    text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists members_division_idx on public.members (division_id);
create index if not exists programs_division_idx on public.programs (division_id);
create index if not exists posts_created_idx on public.posts (created_at desc);
create index if not exists events_date_idx on public.events (date);
create index if not exists aspirations_created_idx on public.aspirations (created_at desc);
create index if not exists aspirations_ip_idx on public.aspirations (ip_hash, created_at);

-- ---------------------------------------------------------------------
-- Trigger: slug otomatis untuk berita & updated_at aspirasi
-- ---------------------------------------------------------------------
create or replace function public.slugify(txt text)
returns text
language sql immutable
as $$
  select coalesce(nullif(left(trim(both '-' from regexp_replace(lower(coalesce(txt, '')), '[^a-z0-9]+', '-', 'g')), 80), ''), 'berita');
$$;

create or replace function public.posts_set_slug()
returns trigger
language plpgsql
as $$
declare
  base text;
  candidate text;
  n int := 2;
begin
  if new.slug is null or new.slug = '' or (tg_op = 'UPDATE' and new.slug is distinct from old.slug) then
    base := public.slugify(coalesce(nullif(new.slug, ''), new.title));
    candidate := base;
    while exists (select 1 from public.posts where slug = candidate and id is distinct from new.id) loop
      candidate := base || '-' || n;
      n := n + 1;
    end loop;
    new.slug := candidate;
  end if;
  return new;
end;
$$;

drop trigger if exists posts_slug on public.posts;
create trigger posts_slug before insert or update on public.posts
  for each row execute function public.posts_set_slug();

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists aspirations_touch on public.aspirations;
create trigger aspirations_touch before update on public.aspirations
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------
alter table public.admins      enable row level security;
alter table public.settings    enable row level security;
alter table public.divisions   enable row level security;
alter table public.members     enable row level security;
alter table public.programs    enable row level security;
alter table public.posts       enable row level security;
alter table public.events      enable row level security;
alter table public.gallery     enable row level security;
alter table public.aspirations enable row level security;

-- Konten publik: semua orang boleh membaca, hanya admin yang boleh mengubah
do $$
declare t text;
begin
  foreach t in array array['settings', 'divisions', 'members', 'programs', 'events', 'gallery'] loop
    execute format('drop policy if exists "Publik dapat membaca" on public.%I', t);
    execute format('create policy "Publik dapat membaca" on public.%I for select using (true)', t);
    execute format('drop policy if exists "Admin dapat mengelola" on public.%I', t);
    execute format('create policy "Admin dapat mengelola" on public.%I for all to authenticated using (public.is_admin()) with check (public.is_admin())', t);
  end loop;
end $$;

-- Berita: publik hanya melihat yang sudah terbit
drop policy if exists "Publik membaca berita terbit" on public.posts;
create policy "Publik membaca berita terbit" on public.posts for select using (published or public.is_admin());
drop policy if exists "Admin dapat mengelola" on public.posts;
create policy "Admin dapat mengelola" on public.posts for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Aspirasi: hanya admin yang dapat mengakses tabel secara langsung.
-- Publik mengirim & melacak lewat fungsi RPC di bawah.
drop policy if exists "Admin dapat mengelola" on public.aspirations;
create policy "Admin dapat mengelola" on public.aspirations for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Admin: sesama admin boleh melihat daftar, hanya superadmin yang boleh mengubah
drop policy if exists "Admin melihat admin" on public.admins;
create policy "Admin melihat admin" on public.admins for select to authenticated using (public.is_admin());
drop policy if exists "Superadmin mengelola admin" on public.admins;
create policy "Superadmin mengelola admin" on public.admins for all to authenticated
  using (public.is_superadmin() and user_id <> auth.uid())
  with check (public.is_superadmin());

-- Hak akses dasar (RLS tetap berlaku)
grant usage on schema public to anon, authenticated;
grant select on public.settings, public.divisions, public.members, public.programs, public.posts, public.events, public.gallery to anon, authenticated;
grant insert, update, delete on public.settings, public.divisions, public.members, public.programs, public.posts, public.events, public.gallery to authenticated;
grant select, insert, update, delete on public.aspirations, public.admins to authenticated;
revoke all on public.aspirations, public.admins from anon;
grant usage, select on all sequences in schema public to authenticated;

-- ---------------------------------------------------------------------
-- Fungsi RPC publik
-- ---------------------------------------------------------------------

-- Kirim aspirasi. Mengembalikan kode tiket. Dibatasi 5 kiriman / 10 menit / IP.
create or replace function public.submit_aspiration(
  p_message   text,
  p_category  text default 'Umum',
  p_name      text default null,
  p_class     text default null,
  p_anonymous boolean default false
)
returns text
language plpgsql volatile security definer
set search_path = public
as $$
declare
  v_ticket text;
  v_ip     text;
  v_hash   text;
  v_msg    text := trim(coalesce(p_message, ''));
begin
  if char_length(v_msg) < 10 then
    raise exception 'Pesan aspirasi minimal 10 karakter' using errcode = '22023';
  end if;
  if char_length(v_msg) > 2000 then
    raise exception 'Pesan maksimal 2000 karakter' using errcode = '22023';
  end if;

  begin
    v_ip := split_part(coalesce(current_setting('request.headers', true)::json ->> 'x-forwarded-for', ''), ',', 1);
  exception when others then
    v_ip := '';
  end;
  v_hash := md5('osis-smaga:' || coalesce(nullif(trim(v_ip), ''), 'unknown'));

  if (select count(*) from public.aspirations
      where ip_hash = v_hash and created_at > now() - interval '10 minutes') >= 5 then
    raise exception 'Terlalu banyak kiriman. Coba lagi beberapa menit lagi.' using errcode = 'P0001';
  end if;

  loop
    v_ticket := 'ASP-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6));
    exit when not exists (select 1 from public.aspirations where ticket = v_ticket);
  end loop;

  insert into public.aspirations (ticket, name, class_name, category, message, anonymous, ip_hash)
  values (
    v_ticket,
    case when p_anonymous then null else nullif(left(trim(coalesce(p_name, '')), 100), '') end,
    case when p_anonymous then null else nullif(left(trim(coalesce(p_class, '')), 20), '') end,
    coalesce(nullif(left(trim(coalesce(p_category, '')), 50), ''), 'Umum'),
    v_msg,
    coalesce(p_anonymous, false),
    v_hash
  );
  return v_ticket;
end;
$$;

-- Lacak aspirasi berdasarkan kode tiket (tanpa identitas pengirim)
create or replace function public.track_aspiration(p_ticket text)
returns table (ticket text, category text, message text, status text, response text, created_at timestamptz, updated_at timestamptz)
language sql stable security definer
set search_path = public
as $$
  select a.ticket, a.category, a.message, a.status, a.response, a.created_at, a.updated_at
  from public.aspirations a
  where a.ticket = upper(trim(p_ticket));
$$;

-- Aspirasi yang sudah selesai ditindaklanjuti (ditampilkan di halaman publik)
create or replace function public.public_aspirations(p_limit int default 6)
returns table (ticket text, category text, message text, status text, response text, updated_at timestamptz)
language sql stable security definer
set search_path = public
as $$
  select a.ticket, a.category, a.message, a.status, a.response, a.updated_at
  from public.aspirations a
  where a.status = 'selesai' and coalesce(a.response, '') <> ''
  order by a.updated_at desc
  limit least(greatest(p_limit, 1), 20);
$$;

-- Statistik untuk beranda
create or replace function public.public_stats()
returns json
language sql stable security definer
set search_path = public
as $$
  select json_build_object(
    'members',          (select count(*) from public.members),
    'divisions',        (select count(*) from public.divisions),
    'programs',         (select count(*) from public.programs),
    'aspirations_done', (select count(*) from public.aspirations where status = 'selesai')
  );
$$;

-- Tambah jumlah baca berita
create or replace function public.increment_post_views(p_slug text)
returns void
language sql volatile security definer
set search_path = public
as $$
  update public.posts set views = views + 1 where slug = p_slug and published;
$$;

grant execute on function public.submit_aspiration(text, text, text, text, boolean) to anon, authenticated;
grant execute on function public.track_aspiration(text) to anon, authenticated;
grant execute on function public.public_aspirations(int) to anon, authenticated;
grant execute on function public.public_stats() to anon, authenticated;
grant execute on function public.increment_post_views(text) to anon, authenticated;
grant execute on function public.is_admin() to anon, authenticated;
grant execute on function public.is_superadmin() to anon, authenticated;

-- ---------------------------------------------------------------------
-- Storage: bucket publik "media" untuk foto & gambar
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do nothing;

drop policy if exists "Media dapat dibaca publik" on storage.objects;
create policy "Media dapat dibaca publik" on storage.objects
  for select using (bucket_id = 'media');

drop policy if exists "Admin dapat mengunggah media" on storage.objects;
create policy "Admin dapat mengunggah media" on storage.objects
  for insert to authenticated with check (bucket_id = 'media' and public.is_admin());

drop policy if exists "Admin dapat mengubah media" on storage.objects;
create policy "Admin dapat mengubah media" on storage.objects
  for update to authenticated using (bucket_id = 'media' and public.is_admin());

drop policy if exists "Admin dapat menghapus media" on storage.objects;
create policy "Admin dapat menghapus media" on storage.objects
  for delete to authenticated using (bucket_id = 'media' and public.is_admin());
